// AUTO-GENERATED by design/reshoot/gen_door_layer.py — DO NOT EDIT BY HAND.
// Regenerate:  python3 design/reshoot/gen_door_layer.py
// Verify:      python3 design/reshoot/gen_door_layer.py --check
//
// The DOM element overlay for the entry stations. The gen'd walk-up carries SOFT, slightly
// warped BAKED TWINS of these five marks (the video was generated from sticker-composited
// pins); this layer lands the crisp originals on top at the hold. Geometry is derived from
// design/door-layer.pen (frame `bi8Au`) — the same table that baked the pins — so the crisp
// mark and its baked twin share one source of truth and cannot drift. Verified: every baked
// element sits within 6.5px of its .pen footprint at 1920 scale (gate <=15px).
//
// All geometry is a PERCENTAGE of the 1920x1080 master frame. The scene paints the video/
// still with object-cover, so StationElementLayer positions this inside a box tracking that
// cover rect — the marks stay glued to the FACADE at any viewport aspect, not to the window.
//
// `cssRotation` is already CSS-signed (Pencil rotates CCW-positive about the top-left corner;
// CSS rotate() is CW-positive). Pin transform-origin to `0 0` and apply it directly.

/** One placement of a mark, as percentages of the 1920x1080 master frame. */
export type ElementPlacement = {
  xPct: number;
  yPct: number;
  wPct: number;
  hPct: number;
  /** Degrees, already negated for CSS (transform-origin must be `0 0`). */
  cssRotation: number;
};

/** Outer drop shadow, in px at the 1920 master scale — multiply by the live cover scale. */
export type ElementShadow = {
  dx: number;
  dy: number;
  blur: number;
  color: string;
};

export type DoorLayerElement = {
  /** The .pen node id — the traceable link back to design/door-layer.pen. */
  id: string;
  name: string;
  asset: string;
  /** Empty string = decorative (aria-hidden). */
  alt: string;
  opacity: number;
  /** The OPEN sign is the diegetic CTA at the door; everything else is inert. */
  isCta: boolean;
  /** Native .pen coords — the close storefront (out1) held frame. */
  door: ElementPlacement;
  /** The same mark on the wide storefront (out0), via the measured out1->out0 transform. */
  street: ElementPlacement;
  doorShadow: ElementShadow | null;
  streetShadow: ElementShadow | null;
  /** Portrait-only override (wordmark). Absent = the mark keeps its landscape placement. */
  doorPortrait?: ElementPlacement;
  streetPortrait?: ElementPlacement;
};

/** Which station's framing a mark is being placed on. */
export type ElementPlacementSet = "door" | "street";

/** Intrinsic size of the master frame every clip and still is authored at. */
export const MASTER_WIDTH = 1920;
export const MASTER_HEIGHT = 1080;

/**
 * The portrait rule: GENUINELY portrait only — taller than it is wide.
 *
 * It used to be `aspect < 16/9`, which was WRONG and shipped a visible bug: a 1161x1015 desktop
 * window (aspect 1.14) is landscape, but 1.14 < 1.78, so the wordmark relocated to the portrait
 * position — centred over the neon — while its BAKED TWIN stayed in the right window. Two
 * wordmarks on screen at once.
 *
 * The relocation exists for ONE reason: at a phone's aspect, object-cover crops the frame's
 * sides so hard that the wordmark (x 1249..1548 of 1920) falls outside the surviving centre
 * column entirely. That is a portrait problem. Every landscape window — however square — still
 * shows the wordmark's native spot, so it must keep its native geometry and stay welded to its
 * twin. There is NO intermediate zone: portrait, or door-native.
 */
export function isPortrait(width: number, height: number): boolean {
  return height > width;
}

/** Resolve a mark's placement for a station framing + orientation. */
export function placementFor(
  el: DoorLayerElement,
  set: ElementPlacementSet,
  portrait: boolean,
): ElementPlacement {
  if (portrait) {
    const override = set === "door" ? el.doorPortrait : el.streetPortrait;
    if (override) return override;
  }
  return set === "door" ? el.door : el.street;
}

/** The matching shadow for a placement set (px at master scale). */
export function shadowFor(
  el: DoorLayerElement,
  set: ElementPlacementSet,
): ElementShadow | null {
  return set === "door" ? el.doorShadow : el.streetShadow;
}

/** The five marks, back-to-front (.pen child order = paint order). */
export const DOOR_LAYER_ELEMENTS: readonly DoorLayerElement[] = [
  {
    id: "DUc4P",
    name: "flyer-right",
    asset: "/door-layer/flyer-grimy-cut.png",
    alt: "",
    opacity: 0.96,
    isCta: false,
    door: {
      xPct: 46.82292,
      yPct: 27.3729,
      wPct: 2.70833,
      hPct: 3.7037,
      cssRotation: -4.0
    },
    street: {
      xPct: 47.79384,
      yPct: 31.29617,
      wPct: 1.66174,
      hPct: 2.27246,
      cssRotation: -4.0927
    },
    doorShadow: {
      dx: 2.0,
      dy: 3.0,
      blur: 6.0,
      color: "rgba(0, 0, 0, 0.4)"
    },
    streetShadow: {
      dx: 1.2271,
      dy: 1.8407,
      blur: 3.6814,
      color: "rgba(0, 0, 0, 0.4)"
    }
  },
  {
    id: "O7vwR",
    name: "flyer-left",
    asset: "/door-layer/flyer-curl-cut.png",
    alt: "",
    opacity: 0.78,
    isCta: false,
    door: {
      xPct: 24.49766,
      yPct: 47.77778,
      wPct: 3.07292,
      hPct: 4.16667,
      cssRotation: 3.0
    },
    street: {
      xPct: 34.10728,
      yPct: 43.85525,
      wPct: 1.88543,
      hPct: 2.55652,
      cssRotation: 2.9073
    },
    doorShadow: {
      dx: 2.0,
      dy: 3.0,
      blur: 6.0,
      color: "rgba(0, 0, 0, 0.4)"
    },
    streetShadow: {
      dx: 1.2271,
      dy: 1.8407,
      blur: 3.6814,
      color: "rgba(0, 0, 0, 0.4)"
    }
  },
  {
    id: "Ve5Sr",
    name: "shade-sticker",
    asset: "/door-layer/shade-sticker-trans.png",
    alt: "",
    opacity: 0.83,
    isCta: false,
    door: {
      xPct: 50.46875,
      yPct: 63.61111,
      wPct: 4.6875,
      hPct: 4.62963,
      cssRotation: -0.0
    },
    street: {
      xPct: 50.05103,
      yPct: 53.52417,
      wPct: 2.87608,
      hPct: 2.84057,
      cssRotation: -0.0927
    },
    doorShadow: null,
    streetShadow: null
  },
  {
    id: "d3oPkd",
    name: "window-wordmark",
    asset: "/door-layer/chunky-wordmark.png",
    alt: "chunkylabs",
    opacity: 0.85,
    isCta: false,
    door: {
      xPct: 65.05208,
      yPct: 12.87037,
      wPct: 15.57292,
      hPct: 15.37037,
      cssRotation: -0.0
    },
    street: {
      xPct: 58.97049,
      yPct: 22.36578,
      wPct: 9.55498,
      hPct: 9.43071,
      cssRotation: -0.0927
    },
    doorShadow: null,
    streetShadow: null,
    doorPortrait: {
      xPct: 43.90625,
      yPct: 8.33333,
      wPct: 12.1875,
      hPct: 12.03704,
      cssRotation: -0.0
    },
    streetPortrait: {
      xPct: 45.99365,
      yPct: 19.61934,
      wPct: 7.47781,
      hPct: 7.38549,
      cssRotation: -0.0927
    }
  },
  {
    id: "NQZHy",
    name: "open-sign",
    asset: "/door-layer/open-sign.png",
    alt: "Come in \u2014 we're open",
    opacity: 0.82,
    isCta: true,
    door: {
      xPct: 49.32518,
      yPct: 32.26233,
      wPct: 3.4375,
      hPct: 11.01852,
      cssRotation: 1.0
    },
    street: {
      xPct: 49.33187,
      yPct: 34.29172,
      wPct: 2.10913,
      hPct: 6.76057,
      cssRotation: 0.9073
    },
    doorShadow: null,
    streetShadow: null
  }
] as const;
